apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.postgresql.primary.initdb.scriptsConfigMap }}
data:
  db.sql: |-
    SELECT 'CREATE DATABASE {{ .Values.postgresql.global.postgresql.auth.database }}'
    WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '{{ .Values.postgresql.global.postgresql.auth.database }}');
  table.sql: |-
    \c {{ .Values.postgresql.global.postgresql.auth.database }};

    CREATE TABLE IF NOT EXISTS {{ .Values.database.table }} (
      id text,
      event_time bigint,

      CONSTRAINT pk PRIMARY KEY (id, event_time)
  );
