apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.name" . }}
type: Opaque
data:
  database.user: {{ .Values.postgresql.global.postgresql.auth.username | b64enc }}
  database.password: {{ .Values.postgresql.global.postgresql.auth.password | b64enc }}
