---
version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:15.4
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./migrations/up:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "PGPASSWORD=${PG_PASSWORD} psql --user=${PG_USER} --host=localhost --port=5432 --dbname=accounts -c \"\\d accounts\" || exit 1" ]
      interval: 1s
      timeout: 5s
      retries: 120
    ports:
      - "5432:5432"

  watcher:
    depends_on:
      postgres:
        condition: service_healthy
    container_name: watcher
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ENDPOINT: ${ENDPOINT}
      PG_HOST: postgres
      PG_PORT: 5432
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DATABASE: accounts
      PG_TABLE: accounts
      LOG_LEVEL: ${LOG_LEVEL}
      ACCOUNTS: ${ACCOUNTS}
