apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.name" . }}
data:
  endpoint: {{ .Values.service.endpoint | quote }}
  accounts: {{ .Values.accounts | toJson | quote }}
  database.host: {{ .Values.postgresql.fullnameOverride | quote }}
  database.port: {{ .Values.postgresql.primary.service.ports.postgresql | quote }}
  database.database: {{ .Values.postgresql.global.postgresql.auth.database | quote }}
  database.table: {{ .Values.database.table | quote }}
