apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.name" . }}
type: Opaque
data:
  database.user: {{ .Values.database.user | b64enc }}
  database.password: {{ .Values.database.password | b64enc }}
