
nameOverride: ""

# Service config
service:
  logLevel: info
  port: 6868
  # https://wiki.polkadot.network/docs/maintain-endpoints
  endpoint: wss://westend-rpc.polkadot.io

# Database config
database:
  host: postgres
  port: 5432
  user: postgres
  password: postgres
  database: accounts
  table: accounts

# Accounts to monitor
accounts:
  - id: 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
    threshold: 2.2

image:
  repo: alexandruplacinta/kusama-monitoring-watcher
  tag: 0.1.0

resources:
  requests:
    memory: 250Mi
    cpu: 250m
  limits:
    memory: 500Mi
    cpu: 500m

kube-prometheus-stack:
  prometheus:
    enabled: true
    agentMode: false
    servicePerReplica:
      port: 9090

  grafana:
    enabled: true
    adminUser: admin
    adminPassword: admin
    forceDeployDatasources: false
    forceDeployDashboards: false
    defaultDashboardsTimezone: utc
    serviceMonitor:
      enabled: true

postgresql:
  fullnameOverride: postgres

  global:
    postgresql:
      auth:
        username: postgres
        password: postgres
        database: accounts

  primary:
    initdb:
      scripts:
        init.sql: |
          SELECT 'CREATE DATABASE accounts'
          WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'accounts'); \gexec

          \c accounts;

          CREATE TABLE IF NOT EXISTS accounts (
            id text PRIMARY KEY,
            event_time bigint
          );
