
# Service config
service:
  logLevel: INFO,
  port: 6868
  endpoint: wss://kusama-rpc.polkadot.io

# Database config
database:
  host: localhost,
  port: 5555,
  user: user,
  password: password,
  database: accounts,
  table: accounts

# Accounts to monitor: JSON string
accounts: "[]"
