
nameOverride: ""

# Service config
service:
  logLevel: info
  port: 6868
  # https://wiki.polkadot.network/docs/maintain-endpoints
  endpoint: wss://westend-rpc.polkadot.io

# Database config
database:
  table: accounts

# Accounts to monitor
accounts:
  - id: 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
    threshold: 2.2

image:
  repo: alexandruplacinta/kusama-monitoring-watcher
  tag: 0.1.0

resources:
  requests:
    memory: 250Mi
    cpu: 250m
  limits:
    memory: 500Mi
    cpu: 500m

kube-prometheus-stack:
  prometheus:
    enabled: true
    agentMode: false
    servicePerReplica:
      port: 9090

  grafana:
    enabled: true
    adminUser: admin
    adminPassword: admin
    forceDeployDatasources: false
    forceDeployDashboards: false
    defaultDashboardsTimezone: utc
    serviceMonitor:
      enabled: true

postgresql:
  fullnameOverride: ""

  global:
    postgresql:
      auth:
        username: ""
        password: ""
        database: accounts

    initdb:
      scriptsConfigMap: ""
